project:
  type: website
  output-dir: docs
  
website:
  title: "JACKIE ERNEST"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - about.qmd
      - documents.qmd
      - applications.qmd
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/CibyL1226/website-creation
      - icon: envelope
        href: mailto:your.email@example.com
      - icon: linkedin
        href: https://www.linkedin.com/in/yourusername
      - icon: google-scholar
        href: https://scholar.google.com/citations?user=YOUR_ID
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Jackie Ernest"

format:
  html:
    theme: cerulean
    toc: true

editor: source

