project:
  type: website
  output-dir: docs
  
website:
  title: "JACKIE ERNEST"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - documents.qmd
      - applications.qmd
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/jackieernest
      - icon: envelope
        href: mailto:jackieernest3@gmail.com
      - icon: book
        href: https://scholar.google.com/citations?user=A0sm6T4AAAAJ&hl=en
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Jackie Ernest"

format:
  html:
    theme: flatly
    toc: true
    css: style.css

editor: source

