name: Quarto Publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pyyaml nbformat ipykernel numpy pandas matplotlib

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site into docs/
        run: quarto render

      - name: Commit docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Auto-update site output in docs" || echo "No changes to commit"
          git push origin main
